[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"

[dependencies]
anyhow = "1.0.104"                                   # error handling
bytes = "1.12.1"                                     # helps manage buffers
chrono = "0.4.45"
mio = { version = "1.2.3", features = ["os-poll", "net"] }
thiserror = "2.0.21"                                # error handling
xxhash-rust = { version = "0.8.19", features = ["xxh3"] }

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
